#!/bin/bash

read -n1 -p "WARNING: this will wipe all *.tar files and copy the metadata.desktop over here (y/n)"

echo

if [ $REPLY == "y" ]; then

    rm *.tar
    rm -Rv ./temp
    cp -Rv . ./temp
    cd ./temp
    command cp -v package/metadata.desktop .
    mv ./package/contents .
    rm -Rv ./package


    tar -cf kickoff-netrunner-$(date +%Y-%d-%h-%H-%M).tar .

    rsync *.tar   kdebuildgitvm@files.kde.org:Downloads -v
else
    echo "ABORTED, DOING NOTHING!"
fi
